# Generated by Django 4.2.7 on 2023-12-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DModel',
            fields=[
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('weight', models.FloatField()),
                ('birth_year', models.DateField()),
            ],
        ),
    ]
